"""Recovery envelope — generated by policy, never by the LLM."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import List


@dataclass
class RecoveryEnvelope:
    id: str
    exception_id: str
    allowed_actions: List[str] = field(default_factory=list)
    forbidden_actions: List[str] = field(default_factory=list)
    max_attempts: int = 3
    expires_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc) + timedelta(minutes=30)
    )
    required_evidence: List[str] = field(default_factory=list)
    required_postconditions: List[str] = field(default_factory=list)

    def is_expired(self, now: datetime | None = None) -> bool:
        now = now or datetime.now(timezone.utc)
        return now > self.expires_at

    def action_permitted(self, action: str) -> bool:
        if action in self.forbidden_actions:
            return False
        return action in self.allowed_actions
